version: "3.9"
services:
  iranstockscrawler:
    build: .
    ports:
     - "1212:1212"
    volumes:
      - files:/IranStocksCrawler/files
    environment:
      - LOG_LEVEL=debug
volumes:   
  files:    