version: "3.9"
services:
  iranstockcrawler:
    build: .
    volumes:
      - .:/opt/app/api
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS:-123#abada@}
    expose:
     - "6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
volumes:
  redis-data:
  redis-conf: